import type { Metadata } from "next";
import { El_Messiri } from "next/font/google";
import "./globals.css";

const elmes = El_Messiri({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={elmes.className}>{children}</body>
    </html>
  );
}
